version: "3"
services:
  ignite-node-1:
    image: apacheignite/ignite:2.10.0
    environment:
      OPTION_LIBS: ignite-rest-http,ignite-aws
      CONFIG_URI: /my-conf.xml
    volumes:
      - ./my-conf.xml:/my-conf.xml

  ignite-node-2:
    image: apacheignite/ignite:2.10.0
    environment:
      OPTION_LIBS: ignite-rest-http,ignite-aws
      CONFIG_URI: /my-conf.xml
    volumes:
      - ./my-conf.xml:/my-conf.xml

  ignite-node-3:
    image: apacheignite/ignite:2.10.0
    environment:
      OPTION_LIBS: ignite-rest-http,ignite-aws
      CONFIG_URI: /my-conf.xml
    volumes:
      - ./my-conf.xml:/my-conf.xml

  ignite-node-4:
    image: apacheignite/ignite:2.10.0
    environment:
      OPTION_LIBS: ignite-rest-http,ignite-aws
      CONFIG_URI: /my-conf.xml
    volumes:
      - ./my-conf.xml:/my-conf.xml

networks:
  default:
    driver: bridge